version: '3.7'

services:
    wwfh_web:
        build: .
        entrypoint: bash /code/docker-entrypoint.sh
        container_name: wwfh_web
        image: wwfh_web
        volumes:
            - .:/code
            - static-content:/static
        ports:
            - "8080:8080"
        depends_on:
            - wwfh_postgres
        links:
            - wwfh_postgres
        environment:
            DATABASE_URL: "postgres://root:postgres@wwfh_postgres:5432/wwfh"

    wwfh_postgres:
        container_name: wwfh_postgres
        image: postgres:11
        environment:
            POSTGRES_DB: wwfh
            POSTGRES_USER: root
            POSTGRES_PASSWORD: postgres
        volumes:
            - /var/lib/postgresql/data/
        ports:
            - "5432:5432"
        restart: always

networks:
    default:
        external:
            name: local

volumes:
    postgres_data:
    static-content: