# Generated by Django 3.1.2 on 2020-10-25 17:30

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('company_statement', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='images/')),
                ('url', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('contract', 'Contract')], max_length=100)),
                ('company_location', models.CharField(max_length=200)),
                ('regional_restrictions', models.CharField(choices=[('design', 'Design'), ('programming', 'Programming'), ('customer_support', 'Customer Support'), ('copy_writing', 'Copy Writing'), ('devops_sys_admin', 'DevOps and Sysadmin'), ('sales_marketing', 'Sales and Marketing'), ('business_mgmt_finance', 'Business Management and Finance'), ('product', 'Product'), ('other', 'All Other Remote')], max_length=100)),
                ('application_url', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='jobs.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='jobs.company')),
            ],
            options={
                'verbose_name': 'Job Post',
                'verbose_name_plural': 'Job Posts',
                'ordering': ['-created_on'],
            },
        ),
    ]
