# Generated by Django 3.1.2 on 2020-10-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20201028_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='company_location',
            new_name='job_location',
        ),
    ]
