# Generated by Django 3.1.2 on 2020-11-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20201028_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='headquarters',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
