# Generated by Django 3.1.2 on 2020-11-02 16:51

from django.db import migrations
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_company_headquarters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=jobs.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
